### ISSUE TITLE
Token is never cached

### ISSUE THREAD

**Issue by robskr** [digitalcz/gosms#103]
**Describe the bug**

Token is never cached as there's a bug in either

A) `ApiKeyCredentials::provide()`

or 

B) `Token`, more specifically `Token::$exp` + `Token::getTtl()`.

GoSMS API already returns TTL in `expires_in` (see [docs](https://doc.gosms.eu/#tag/AccessToken)), but it is passed to `Token` as expiration timestamp in `ApiKeyCredentials::provide()`.

`Token::getTtl()` as it is now implemented returns a negative timestamp.

**To Reproduce**

1. Use cache
2. Log bearer tokens or monitor requests
3. Send at least two texts in quick succession
4. See multiple tokens/requests to issue token

It's also reproducible using tests - you just have to fix wrong test.

1. Fix `CachedCredentialsTest::testProvide()` mock with more representative value: `time() + 300` -> `300`.
2. Run tests
3. See failing test

**Expected behavior**

Tokens are reused until they expire.

**Comment by spajxo** [comment]
Thanks for the fix @robskr
